version: "2.4"
services:

  nb-api-jupyter:
    container_name: nb-api-jupyter
    image: jupyter/tensorflow-notebook:ubuntu-20.04
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/
      - ./config:/home/jovyan/.jupyter
